- name: Ensure group 'developers' exists
  group:
    name: developers
    state: present

- name: Create the user 'bender'
  user:
    name: bender
    shell: /bin/bash
    password: $6$kQMqV39TkhRYsPbk$vGoai3v9zbJOx5u4iWlpesHsY4GuqUL7HyWwKoMMMX7dubV29ASY.xYLtVg13dFCv2hUs3GkNHc6T0i7fzMSd0

- name: Assign 'bender' to the 'developers' group
  user:
    name: bender
    groups: developers
    append: yes

- name: Create a directory named 'engineering'
  file:
    path: /opt/engineering
    state: directory
    mode: 0750
    group: developers

- name: Create a file in the engineering directory
  file:
    path: "/opt/engineering/private.txt"
    state: touch
    mode: 0770
    group: developers
